next_session: 30th Sep
next_session_long: Sat 30th Sept 2017

# SEO settings
title: "CoderDojo York"
title2: "" # default: ""
description: "Free coding classes for all young people 7-17 in York, UK"
keywords: "coderdojo, york, coding, free for kids, programming, classes"
url: http://yorkdojo.github.io # site url
baseurl: null

google_analytics: UA-92516170-1
repo: http://github.com/YorkDojo/yorkdojo.github.io
cover: /assets/images/york-dojo-logo-web.png
twitter_username: "CoderDojoYork"
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

collections:
  worksheets:
    output: true

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Andy Callaghan"
  url      : https://yorkdojo.github.io
  github   : https://github.com/YorkDojo
  twitter  : https://twitter.com/CoderDojoYork
  facebook : https://www.facebook.com/CoderDojoYork/

# social settings
og_locale: "en_GB"
twitter_card: "summary_large_image"
twitter_site: "@CoderDojoYork"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
